import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          {/* FLEX WRAPPER */}
          <div className="flex min-h-screen w-full">
            
            {/* SIDEBAR */}
            <AppSidebar />

            {/* MAIN CONTENT */}
            <main className="flex-1 flex flex-col">
              
              {/* HEADER / TRIGGER */}
              <div className="px-4 py-2">
                <SidebarTrigger />
              </div>

              {/* PAGE CONTENT */}
              <div className="flex-1 flex justify-center">
                <div className="w-full max-w-7xl px-4">
                  {children}
                </div>
              </div>

            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}

