"use client";

import { useState } from "react";
import { Sparkles, Loader2 } from "lucide-react";

interface AIContentGeneratorProps {
    onGenerate: (content: string) => void;
}

export default function AIContentGenerator({ onGenerate }: AIContentGeneratorProps) {
    const [topic, setTopic] = useState("");
    const [tone, setTone] = useState("professional");
    const [isGenerating, setIsGenerating] = useState(false);

    const handleGenerate = async () => {
        if (!topic.trim()) return;

        setIsGenerating(true);
        // Placeholder for actual AI generation logic
        setTimeout(() => {
            const generatedContent = `<h2>Generated Content for: ${topic}</h2><p>This is a placeholder for the content generated by AI with a <strong>${tone}</strong> tone. In the next phase, this will connect to the Gemini API.</p>`;
            onGenerate(generatedContent);
            setIsGenerating(false);
            setTopic("");
        }, 1500);
    };

    return (
        <div className="space-y-4">
            <div>
                <label htmlFor="topic" className="block text-sm font-medium text-zinc-400 mb-1">
                    Topic / Prompt
                </label>
                <textarea
                    id="topic"
                    rows={3}
                    value={topic}
                    onChange={(e) => setTopic(e.target.value)}
                    placeholder="What do you want to write about?"
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-md p-2 text-zinc-200 focus:outline-none focus:border-blue-500 transition-colors resize-none"
                />
            </div>

            <div>
                <label htmlFor="tone" className="block text-sm font-medium text-zinc-400 mb-1">
                    Tone
                </label>
                <select
                    id="tone"
                    value={tone}
                    onChange={(e) => setTone(e.target.value)}
                    className="w-full bg-zinc-950 border border-zinc-800 rounded-md p-2 text-zinc-200 focus:outline-none focus:border-blue-500 transition-colors"
                >
                    <option value="professional">Professional</option>
                    <option value="casual">Casual</option>
                    <option value="enthusiastic">Enthusiastic</option>
                    <option value="informative">Informative</option>
                    <option value="persuasive">Persuasive</option>
                </select>
            </div>

            <button
                onClick={handleGenerate}
                disabled={isGenerating || !topic.trim()}
                className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white font-medium py-2 px-4 rounded-md transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
                {isGenerating ? (
                    <Loader2 className="animate-spin" size={18} />
                ) : (
                    <Sparkles size={18} />
                )}
                {isGenerating ? "Generating..." : "Generate Content"}
            </button>
        </div>
    );
}
